# Generated by Django 4.1.2 on 2022-10-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fec_alta', models.CharField(max_length=16, verbose_name='Fecha alta')),
                ('user_name', models.CharField(max_length=16, verbose_name='Nombre de usuario')),
                ('codigo_zip', models.CharField(max_length=16, verbose_name='Código ZIP')),
                ('credit_card_num', models.CharField(max_length=16, verbose_name='Número tarjeta de crédito')),
                ('credit_card_ccv', models.CharField(max_length=16, verbose_name='CCV tarjeta de crédito')),
                ('cuenta_numero', models.CharField(max_length=16, verbose_name='Número cuenta')),
                ('direccion', models.CharField(max_length=16, verbose_name='Dirección')),
                ('geo_latitud', models.CharField(max_length=16, verbose_name='Latitud')),
                ('geo_longitud', models.CharField(max_length=16, verbose_name='Longitud')),
                ('color_favorito', models.CharField(max_length=16, verbose_name='Color favorito')),
                ('foto_dni', models.CharField(max_length=16, verbose_name='Foto')),
                ('ip', models.CharField(max_length=16, verbose_name='IP')),
                ('auto', models.CharField(max_length=16, verbose_name='Auto')),
                ('auto_modelo', models.CharField(max_length=16, verbose_name='Modelo Auto')),
                ('auto_tipo', models.CharField(max_length=16, verbose_name='Tipo Auto')),
                ('auto_color', models.CharField(max_length=16, verbose_name='Color Auto')),
                ('avatar', models.CharField(max_length=16, verbose_name='Avatar')),
                ('fec_birthday', models.CharField(max_length=16, verbose_name='Fecha Nacimiento')),
            ],
        ),
    ]
